x-base-service: &base-service
    env_file: ./.env
    restart: on-failure

services:
    postgres:
        <<: *base-service
        image: postgres:14.3-alpine
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        <<: *base-service
        image: redis:7-alpine
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - redis_data:/data

volumes:
    pgdata:
    redis_data:
