"""fix: новая миграция без схемы для модели users

Revision ID: 014618344c04
Revises: 
Create Date: 2022-12-24 13:47:25.170161

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "014618344c04"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Наименование роли", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_roles")),
    )
    op.create_table(
        "users_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Имя", sa.String(length=150), nullable=True),
        sa.Column("Фамилия", sa.String(length=150), nullable=True),
        sa.Column("Отчество", sa.String(length=150), nullable=True),
        sa.Column("Дата рождения", sa.DateTime(), nullable=True),
        sa.Column("Телефон пользователя", sa.SmallInteger(), nullable=True),
        sa.Column("Id пользователя в телеграм", sa.Integer(), nullable=True),
        sa.Column("Роль пользователя", sa.Integer(), nullable=False),
        sa.Column("Время удаления", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Роль пользователя"],
            ["users_roles.id"],
            name=op.f("fk_users_users_Роль пользователя_users_roles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_users")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_users")
    op.drop_table("users_roles")
    # ### end Alembic commands ###
