"""Реализована схема meetings

Revision ID: 07931b05a239
Revises: 7fcdd7e0fdab
Create Date: 2022-12-21 16:46:40.326845

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "07931b05a239"
down_revision = "7fcdd7e0fdab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA meetings")
    op.create_table(
        "meeting_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Название встречи", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_types")),
        schema="meetings",
    )
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Клиент", sa.Integer(), nullable=False),
        sa.Column("Психолог", sa.Integer(), nullable=False),
        sa.Column("Тип встречи", sa.Integer(), nullable=False),
        sa.Column("Обращение к психологу", sa.Text(), nullable=True),
        sa.Column("Бал за тест", sa.SmallInteger(), nullable=False),
        sa.Column("Временной слот", sa.DateTime(), nullable=False),
        sa.Column("Время удаления", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Клиент"], ["general.users.id"], name=op.f("fk_meetings_Клиент_users")
        ),
        sa.ForeignKeyConstraint(
            ["Психолог"], ["general.users.id"], name=op.f("fk_meetings_Психолог_users")
        ),
        sa.ForeignKeyConstraint(
            ["Тип встречи"],
            ["meetings.meeting_types.id"],
            name=op.f("fk_meetings_Тип встречи_meeting_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        schema="meetings",
    )
    op.create_table(
        "meeting_feedbacks_completed",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Встреча", sa.Integer(), nullable=False),
        sa.Column("Клиент", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["Встреча"],
            ["meetings.meetings.id"],
            name=op.f("fk_meeting_feedbacks_completed_Встреча_meetings"),
        ),
        sa.ForeignKeyConstraint(
            ["Клиент"],
            ["general.users.id"],
            name=op.f("fk_meeting_feedbacks_completed_Клиент_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_feedbacks_completed")),
        schema="meetings",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meeting_feedbacks_completed", schema="meetings")
    op.drop_table("meetings", schema="meetings")
    op.drop_table("meeting_types", schema="meetings")
    op.execute("DROP SCHEMA meetings")
    # ### end Alembic commands ###
