"""Added psychologist_info

Revision ID: 1d6756420e79
Revises: 3f920242e8ea
Create Date: 2022-12-28 13:47:23.080387

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1d6756420e79"
down_revision = "3f920242e8ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "psychologist_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("cal_link", sa.Text(), nullable=True),
        sa.Column("cal_pass", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_psychologist_info_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_psychologist_info")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("psychologist_info")
    # ### end Alembic commands ###
