"""Реализована схема meetings

Revision ID: 2977aab5bdca
Revises: f7cc230c4714
Create Date: 2022-12-20 21:46:05.780779

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2977aab5bdca"
down_revision = "f7cc230c4714"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA general")
    op.execute("CREATE SCHEMA meetings")
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Наименование роли", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        schema="general",
    )
    op.create_table(
        "meeting_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Название встречи", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_types")),
        schema="meetings",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Имя", sa.String(length=150), nullable=True),
        sa.Column("Фамилия", sa.String(length=150), nullable=True),
        sa.Column("Отчество", sa.String(length=150), nullable=True),
        sa.Column("Дата рождения", sa.DateTime(), nullable=True),
        sa.Column("Телефон пользователя", sa.SmallInteger(), nullable=True),
        sa.Column("Id пользователя в телеграм", sa.Integer(), nullable=True),
        sa.Column("Роль пользователя", sa.Integer(), nullable=False),
        sa.Column("Время удаления", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Роль пользователя"],
            ["general.roles.id"],
            name=op.f("fk_users_Роль пользователя_roles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema="general",
    )
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Клиент", sa.Integer(), nullable=False),
        sa.Column("Психолог", sa.Integer(), nullable=False),
        sa.Column("Тип встречи", sa.Integer(), nullable=False),
        sa.Column("Обращение к психологу", sa.Text(), nullable=True),
        sa.Column("Бал за тест", sa.SmallInteger(), nullable=False),
        sa.Column("Временной слот", sa.DateTime(), nullable=False),
        sa.Column("Время удаления", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Клиент"], ["general.users.id"], name=op.f("fk_meetings_Клиент_users")
        ),
        sa.ForeignKeyConstraint(
            ["Психолог"], ["general.users.id"], name=op.f("fk_meetings_Психолог_users")
        ),
        sa.ForeignKeyConstraint(
            ["Тип встречи"],
            ["meetings.meeting_types.id"],
            name=op.f("fk_meetings_Тип встречи_meeting_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        schema="meetings",
    )
    op.create_table(
        "meeting_feedbacks_completed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Встреча", sa.Integer(), nullable=False),
        sa.Column("Клиент", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["Встреча"],
            ["meetings.meetings.id"],
            name=op.f("fk_meeting_feedbacks_completed_Встреча_meetings"),
        ),
        sa.ForeignKeyConstraint(
            ["Клиент"],
            ["general.users.id"],
            name=op.f("fk_meeting_feedbacks_completed_Клиент_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_feedbacks_completed")),
        schema="meetings",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meeting_feedbacks_completed", schema="meetings")
    op.drop_table("meetings", schema="meetings")
    op.drop_table("users", schema="general")
    op.drop_table("meeting_types", schema="meetings")
    op.drop_table("roles", schema="general")
    op.execute("DROP SCHEMA meetings")
    op.execute("DROP SCHEMA general")
    # ### end Alembic commands ###
