"""Added username field to psychologist_info

Revision ID: 37d006c42d2d
Revises: 1d6756420e79
Create Date: 2023-01-12 17:49:08.442054

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "37d006c42d2d"
down_revision = "1d6756420e79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("psychologist_info", sa.Column("cal_username", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("psychologist_info", "cal_username")
    # ### end Alembic commands ###
