"""add QuestionType

Revision ID: 3f920242e8ea
Revises: 72e4b471e41b
Create Date: 2022-12-27 13:29:32.407149

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f920242e8ea"
down_revision = "72e4b471e41b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True, comment="Название типа вопроса"),
        sa.Column(
            "validation_regexp",
            sa.Text(),
            nullable=True,
            comment="Возможная валидация ответа на вопрос с помощью regexp",
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Время удаления"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_types")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_types")
    # ### end Alembic commands ###
