"""feat: add QuestionType model

Revision ID: 4ff4236078f0
Revises: 07931b05a239
Create Date: 2022-12-26 14:56:29.604561

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ff4236078f0"
down_revision = "07931b05a239"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True, comment="Название типа вопроса"),
        sa.Column(
            "validation_regexp",
            sa.Text(),
            nullable=True,
            comment="Возможная валидация ответа на вопрос с помощью regexp",
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Время удаления"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_types")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_types")
    # ### end Alembic commands ###
