"""add Question model

Revision ID: 4ff6df586479
Revises: 3f920242e8ea
Create Date: 2022-12-29 12:44:16.560741

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ff6df586479"
down_revision = "3f920242e8ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("question_type_id", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Время удаления"),
        sa.ForeignKeyConstraint(
            ["question_type_id"],
            ["question_types.id"],
            name=op.f("fk_questions_question_type_id_question_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    # ### end Alembic commands ###
