"""fix: новая миграция без схемы для модели meetings

Revision ID: 595bbbec2ef4
Revises: 014618344c04
Create Date: 2022-12-24 13:51:49.342604

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "595bbbec2ef4"
down_revision = "014618344c04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings_meeting_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Название встречи", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings_meeting_types")),
    )
    op.create_table(
        "meetings_meetings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Клиент", sa.Integer(), nullable=False),
        sa.Column("Психолог", sa.Integer(), nullable=False),
        sa.Column("Тип встречи", sa.Integer(), nullable=False),
        sa.Column("Обращение к психологу", sa.Text(), nullable=True),
        sa.Column("Бал за тест", sa.SmallInteger(), nullable=False),
        sa.Column("Временной слот", sa.DateTime(), nullable=False),
        sa.Column("Время удаления", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Клиент"], ["users_users.id"], name=op.f("fk_meetings_meetings_Клиент_users_users")
        ),
        sa.ForeignKeyConstraint(
            ["Психолог"], ["users_users.id"], name=op.f("fk_meetings_meetings_Психолог_users_users")
        ),
        sa.ForeignKeyConstraint(
            ["Тип встречи"],
            ["meetings_meeting_types.id"],
            name=op.f("fk_meetings_meetings_Тип встречи_meetings_meeting_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings_meetings")),
    )
    op.create_table(
        "meetings_meeting_feedbacks_completed",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Встреча", sa.Integer(), nullable=False),
        sa.Column("Клиент", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["Встреча"],
            ["meetings_meetings.id"],
            name=op.f("fk_meetings_meeting_feedbacks_completed_Встреча_meetings_meetings"),
        ),
        sa.ForeignKeyConstraint(
            ["Клиент"],
            ["users_users.id"],
            name=op.f("fk_meetings_meeting_feedbacks_completed_Клиент_users_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings_meeting_feedbacks_completed")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meetings_meeting_feedbacks_completed")
    op.drop_table("meetings_meetings")
    op.drop_table("meetings_meeting_types")
    # ### end Alembic commands ###
