"""Реализована схема general

Revision ID: 7fcdd7e0fdab
Revises:
Create Date: 2022-12-21 16:44:34.139595

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7fcdd7e0fdab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA general")
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Наименование роли", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        schema="general",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Имя", sa.String(length=150), nullable=True),
        sa.Column("Фамилия", sa.String(length=150), nullable=True),
        sa.Column("Отчество", sa.String(length=150), nullable=True),
        sa.Column("Дата рождения", sa.DateTime(), nullable=True),
        sa.Column("Телефон пользователя", sa.SmallInteger(), nullable=True),
        sa.Column("Id пользователя в телеграм", sa.Integer(), nullable=True),
        sa.Column("Роль пользователя", sa.Integer(), nullable=False),
        sa.Column("Время удаления", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Роль пользователя"],
            ["general.roles.id"],
            name=op.f("fk_users_Роль пользователя_roles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema="general",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users", schema="general")
    op.drop_table("roles", schema="general")
    op.execute("DROP SCHEMA general")
    # ### end Alembic commands ###
