"""added user field in Test model

Revision ID: 90b4f35bf2b7
Revises: bf3e4ccd019c
Create Date: 2022-12-30 00:47:23.737348

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "90b4f35bf2b7"
down_revision = "bf3e4ccd019c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tests", sa.Column("created_by", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_tests_created_by_users"), "tests", "users", ["created_by"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tests_created_by_users"), "tests", type_="foreignkey")
    op.drop_column("tests", "created_by")
    # ### end Alembic commands ###
