"""add user_time_slot

Revision ID: c04755e67cf6
Revises: 0656f5c8fb7a
Create Date: 2023-01-19 14:17:21.781609

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c04755e67cf6"
down_revision = "0656f5c8fb7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_time_slots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date_start", sa.DateTime(), nullable=True, comment="Время начала"),
        sa.Column("date_end", sa.DateTime(), nullable=True, comment="Время конца"),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Время удаления"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_time_slots_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_time_slots")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_time_slots")
    # ### end Alembic commands ###
