"""добавлена модель question_types

Revision ID: c1e63e9e79e2
Revises: 07931b05a239
Create Date: 2022-12-21 17:56:43.483414

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c1e63e9e79e2"
down_revision = "07931b05a239"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время обновления", sa.DateTime(), nullable=True),
        sa.Column("Тип вопроса", sa.String(length=256), nullable=True),
        sa.Column("Валидация ответа", sa.Text(), nullable=True),
        sa.Column("Время удаления", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_types")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_types")
    # ### end Alembic commands ###
