"""Добавлена модель Meeting

Revision ID: c92054689c4e
Revises: 429d5433be47
Create Date: 2022-12-20 07:55:42.394334

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c92054689c4e"
down_revision = "429d5433be47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meeting_types",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_types")),
    )
    op.create_table(
        "meetings",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("Клиент", postgresql.UUID(), nullable=False),
        sa.Column("Психолог", postgresql.UUID(), nullable=False),
        sa.Column("Тип встречи", postgresql.UUID(), nullable=False),
        sa.Column("Комментарий", sa.Text(), nullable=True),
        sa.Column("Бал за тест", sa.SmallInteger(), nullable=False),
        sa.Column("Временной слот", sa.DateTime(), nullable=False),
        sa.Column("Время создания", sa.DateTime(), nullable=True),
        sa.Column("Время удаления", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["Клиент"], ["users.id"], name=op.f("fk_meetings_Клиент_users")),
        sa.ForeignKeyConstraint(
            ["Психолог"], ["users.id"], name=op.f("fk_meetings_Психолог_users")
        ),
        sa.ForeignKeyConstraint(
            ["Тип встречи"],
            ["meeting_types.id"],
            name=op.f("fk_meetings_Тип встречи_meeting_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meetings")
    op.drop_table("meeting_types")
    # ### end Alembic commands ###
