"""fix: дополнение к полю name

Revision ID: d85b329bcf5c
Revises: 595bbbec2ef4
Create Date: 2022-12-24 14:07:04.320956

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d85b329bcf5c"
down_revision = "595bbbec2ef4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meetings_meeting_types",
        "Название встречи",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_meetings_meeting_types_Название встречи"),
        "meetings_meeting_types",
        ["Название встречи"],
    )
    op.create_unique_constraint(
        op.f("uq_users_roles_Наименование роли"), "users_roles", ["Наименование роли"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_roles_Наименование роли"), "users_roles", type_="unique")
    op.drop_constraint(
        op.f("uq_meetings_meeting_types_Название встречи"), "meetings_meeting_types", type_="unique"
    )
    op.alter_column(
        "meetings_meeting_types",
        "Название встречи",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    # ### end Alembic commands ###
