"""Add model TestCompleted

Revision ID: f17e21132cf4
Revises: 3564fbb8381f
Create Date: 2023-01-06 14:38:40.900131

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f17e21132cf4"
down_revision = "3564fbb8381f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_completed",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="Время удаления"),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name=op.f("fk_test_completed_test_id_tests")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_test_completed_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_completed")),
        sa.UniqueConstraint("user_id", "test_id", name="unique_test_completed"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_completed")
    # ### end Alembic commands ###
