"""Add TestProgress model

Revision ID: f464f785c3ca
Revises: d6a45f691f77
Create Date: 2022-12-30 19:47:49.727632

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f464f785c3ca"
down_revision = "d6a45f691f77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_questions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("order_num", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_test_questions_question_id_questions")
        ),
        sa.ForeignKeyConstraint(
            ["test_id"], ["tests.id"], name=op.f("fk_test_questions_test_id_tests")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_questions")),
    )
    op.create_table(
        "test_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("test_question_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_question_id"],
            ["test_questions.id"],
            name=op.f("fk_test_progress_test_question_id_test_questions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_test_progress_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_progress")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_progress")
    op.drop_table("test_questions")
    # ### end Alembic commands ###
