from enum import Enum


class States(str, Enum):
    RELOCATE_MEETING = 'RELOCATE_MEETING'
    CHOOSE_MEETING = 'CHOOSE_MEETING '
    TYPING_MEETING_CANCEL = "TYPING_MEETING_CANCEL"
    TYPING_PHONE = "TYPING_PHONE"
    TYPING_FIRST_NAME = "TYPING_FIRST_NAME"
    TYPING_LAST_NAME = "TYPING_LAST_NAME"
    TYPING_AGE = "TYPING_AGE"
    TYPING_TEST_SCORE = "TYPING_TEST_SCORE"
    TYPING_MEETING_FORMAT = "TYPING_MEETING_FORMAT"
    TYPING_TIME_SLOT = "TYPING_TIME_SLOT"
    TYPING_MEETING_CONFIRM = "TYPING_MEETING_CONFIRM"
