# Generated by Django 4.1.5 on 2023-03-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0016_alter_crontabschedule_timezone"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllUsersNotification",
            fields=[
                (
                    "periodictask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                ("text", models.TextField()),
            ],
            bases=("django_celery_beat.periodictask",),
        ),
    ]
