# Generated by Django 4.1.7 on 2023-04-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_allusersnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Адрес кабинета"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Отчество"),
        ),
    ]
