# Generated by Django 4.1.5 on 2023-01-30 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата старта"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeslots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Таймслот",
                "verbose_name_plural": "Таймслоты",
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата старта"),
                ),
                (
                    "format",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(10, "онлайн"), (20, "очно")],
                        default=10,
                        null=True,
                        verbose_name="Формат встречи",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Психолог",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Консультация",
                "verbose_name_plural": "Консультации",
                "ordering": ["id"],
            },
        ),
    ]
