# Generated by Django 4.1.7 on 2023-03-21 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Запрос к психологу"
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата старта"),
                ),
                (
                    "format",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(10, "онлайн"), (20, "очно")],
                        default=10,
                        null=True,
                        verbose_name="Формат встречи",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Психолог",
                    ),
                ),
            ],
            options={
                "verbose_name": "Консультация",
                "verbose_name_plural": "Консультации",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата старта"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeslots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Таймслот",
                "verbose_name_plural": "Таймслоты",
            },
        ),
        migrations.CreateModel(
            name="MeetingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст отзыва")),
                ("score", models.SmallIntegerField(blank=True, null=True, verbose_name="Оценка")),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="schedule.meeting",
                        verbose_name="Консультация",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="timeslot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslot_meetings",
                to="schedule.timeslot",
                verbose_name="Таймслот",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_meetings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пациент",
            ),
        ),
        migrations.RemoveField(
            model_name="meetingfeedback",
            name="score",
        ),
        migrations.AddField(
            model_name="meetingfeedback",
            name="better_score",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Оценка улучшений после консультации"
            ),
        ),
        migrations.AddField(
            model_name="meetingfeedback",
            name="comfort_score",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Оценка комфорта на консультации"
            ),
        ),
        migrations.CreateModel(
            name="MeetingPeriodicTask",
            fields=[
                (
                    "periodictask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_periodic_task",
                        to="schedule.meeting",
                        verbose_name="Консультация",
                    ),
                ),
            ],
            bases=("django_celery_beat.periodictask",),
        ),
    ]
