# Generated by Django 4.1.6 on 2023-02-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="comment",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Запрос к психологу"
            ),
        ),
    ]
