# Generated by Django 4.1.5 on 2023-02-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_meeting_timeslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="timeslot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslot_meetings",
                to="schedule.timeslot",
                verbose_name="Таймслот",
            ),
        ),
    ]
