# Generated by Django 4.1.5 on 2023-02-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="is_correct",
        ),
        migrations.RemoveField(
            model_name="question",
            name="score",
        ),
        migrations.AddField(
            model_name="answer",
            name="value",
            field=models.SmallIntegerField(default=0, null=True, verbose_name="Баллы"),
        ),
        migrations.AddField(
            model_name="question",
            name="order_num",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Порядковый номер"),
        ),
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="content.test",
            ),
        ),
    ]
