# Generated by Django 4.1.5 on 2023-02-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_answer_is_correct_remove_question_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testprogress",
            name="test",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answered",
                to="content.test",
            ),
        ),
    ]
