# Generated by Django 4.1.5 on 2023-02-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_testprogress_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testprogress",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in",
                to="content.answer",
            ),
        ),
    ]
