# Generated by Django 4.1.5 on 2023-02-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_testprogress_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testprogress",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="testprogress",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="testprogress",
            name="question",
        ),
        migrations.RemoveField(
            model_name="testprogress",
            name="test",
        ),
        migrations.DeleteModel(
            name="TestCompleted",
        ),
        migrations.DeleteModel(
            name="TestProgress",
        ),
    ]
