# Generated by Django 4.1.5 on 2023-03-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questioning", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testprogress",
            options={
                "verbose_name": "Ответ на вопрос теста",
                "verbose_name_plural": "Ответы на вопрос теста",
            },
        ),
    ]
