from enum import Enum

from telegram.ext import ConversationHandler


class BotState(str, Enum):
    MENU_START_SELECTING_LEVEL = "MENU_START_SELECTING_LEVEL"
    MENU_ADMIN_SELECTING_LEVEL = "MENU_ADMIN_SELECTING_LEVEL"
    MENU_TEST_SELECTING_LEVEL = "MENU_TEST_SELECTING_LEVEL"
    MENU_MEETING_SELECTING_LEVEL = "MENU_MEETING_SELECTING_LEVEL"
    QUESTIONING = "QUESTIONING"
    STOPPING = "STOPPING"
    END = ConversationHandler.END
    ERROR = "ERROR"


class MeetingFormat(int, Enum):
    ONLINE = 10
    OFFLINE = 20


RANDOM_STRING_CHARS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
DO_NOTHING_SIGN = "-"
KEY_RESULTS_FOR_PAGINATED_RESPONSE = "results"
